######################################################################
##
## Filename: memram_tb.udo
## Created on: Sat Mar 16 17:52:22 Hora oficial do Brasil 2024
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
